# Generated by Django 3.2 on 2021-04-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('country_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('screenSize', models.PositiveIntegerField()),
                ('inStock', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.brand')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phones.manufacturer')),
            ],
        ),
    ]
