# Generated by Django 3.2 on 2021-04-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_mobiles_screensize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='inStock',
            new_name='in_stock',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='screenSize',
            new_name='screen_size',
        ),
    ]
